### PR TITLE
Duplicate seat and date for booking

### PR DESCRIPTION
**Pull request by Brian-O-TNA**
Allows seats to be reallocated to another booking on the same date if existing booking is cancelled.  Prevents race condition which could lead to the same seat being allocated to two bookings.

### CODE REVIEW

**Comment by Puththiran** [comment]
Without the trigger can't you check before updating the seatId whether the seatid is already used or not rather than rely on a trigger?

**Comment by Brian-O-TNA** [comment]
You could of course do it that weay but then you're holding the transaction for longer anjd from the application layer and potentially impacting other users. Very unlikely the trigger would be hit in practice.  Stored procedure to do the update with transaction would be another alternative.

**Comment by Brian-O-TNA** [comment]
So the trigger is really a backstop for a race condition that is unlikely to be hit in practice and saves the transaction overhead.

**Comment by Brian-O-TNA** [comment]
OK following discussion this morning, I've replaced the trigger with a stored procedure to do the update within the transaction.

**Review by Puththiran — APPROVED** [review]

**Pull request merged**
